version: 2

before:
  hooks:
    - go mod tidy
builds:
- main: .
  binary: ali
  goos:
    - freebsd
    - darwin
    - linux
    - windows
  goarch:
    - amd64
    - arm
    - arm64
    - 386
    - ppc64le
    - s390x
    - mips64
    - mips64le
  goarm:
    - 6
    - 7
  env:
    - CGO_ENABLED=0
  ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
  ignore:
      - goos: windows
        goarch: arm64

archives:
  -
    name_template: >-
      {{- .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}


checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  filters:
    exclude:
    - '^test:'

brews:
  - repository:
      owner: nakabonne
      name: homebrew-ali
    homepage: 'https://github.com/nakabonne/ali'
    description: 'Generate HTTP load and plot the results in real-time'

nfpms:
  - license: MIT
    maintainer: Ryo Nakao <ryo@nakao.dev>
    homepage: https://github.com/nakabonne/ali
    description: "Generate HTTP load and plot the results in real-time"
    formats:
      - rpm
      - deb

dockers:
  - dockerfile: Dockerfile
    goarch: amd64
    image_templates:
      - "italovalcy/ali:latest"
      - "italovalcy/ali:{{ .Tag }}"
      - "italovalcy/ali:v{{ .Major }}.{{ .Minor }}"
  - dockerfile: Dockerfile
    goarch: arm64
    image_templates:
      - "italovalcy/ali:latest"
      - "italovalcy/ali:{{ .Tag }}"
      - "italovalcy/ali:v{{ .Major }}.{{ .Minor }}"
